spring:
  datasource:
    username: root
    password: 1
    url: jdbc:mysql://localhost:3306/pj?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/templates
logging:
  level:
    com.AISubtitles.Server.mapper: debug
server:
  port: 8084
prop:
  upload-folder: ./files
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
